name: monthly

on:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  monthly:
    name: monthly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: monthly

      - name: Merge main into monthly
        run: |
          git fetch origin main
          git reset --hard origin/main
          git push -f
